export { BibliotecasDigitalesPage } from "./RecursosElectronicosPages/BibliotecasDigitalesPage/BibliotecasDigitalesPage";
export { DiccionariosPage } from "./RecursosElectronicosPages/DiccionariosPage/DiccionariosPage";
export { EbooksPage } from "./RecursosElectronicosPages/EbooksPage/EbooksPage";
export { NormasPage } from "./RecursosElectronicosPages/NormasPage/NormasPage";
export { RevistasElectronicasPage } from "./RecursosElectronicosPages/RevistasElectronicasPage/RevistasElectronicasPage";
export { LineamientosPage } from "./NosotrosPages/LineamientosPage/LineamientosPage";
export { FilosofiaPage } from "./NosotrosPages/FilosofiaPage/FilosofiaPage";
export { BaseDeDatosPage } from "./RecursosElectronicosPages/BaseDeDatosPage/BaseDeDatosPage";
export { InicioPage } from "./InicioPage/InicioPage";